# Generated by Django 2.2.6 on 2019-11-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='featurebuilding',
            table='building',
        ),
    ]
